config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/deflavour', to: 'pages#deflavour'
  get '/caravana', to: 'pages#caravana'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def deflavour
  end

  def caravana
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paul Fournier | Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <title>Paul Fournier</title>
    <link href="../style/application.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <style>@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@500&display=swap');</style>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/caravana.html.erb
<div class="container">
  <h1 class="title-product"> Caravana </h1>
  <div class="product-photos">
    <div class="big-card" style="height:400px;width:50%">

      <img src="https://res.cloudinary.com/dm52xbw1e/image/upload/v1662968667/caravana_wpxs13.png" alt="Caravana" style="width:100%; height:100%;border-radius: 5px;">
    </div>
    <div class="cards-feature" style="height:400px;width:50%">
      <div class="card-category" style="background-image: url(https://res.cloudinary.com/dm52xbw1e/image/upload/v1663162374/localhost_3000_vans_2_q2dr3n.png)">
      </div>
      <div class="card-category" style="background-image: url(https://res.cloudinary.com/dm52xbw1e/image/upload/v1663162799/caravana-adrih1.herokuapp.com_dashboard.78_lqyrel.png)">
      </div>
    </div>
  </div>
  <div class="product-infos">
    <div class="infos-special">
      <h4>Projet d'étude</h4>
      <p>Site crée pendant ma formation au Wagon.</p>
    </div>
    <div class="product-base">
      <h4>A propos</h4>
      <p>Ce site est une copie de Airbnb permettant la mise en relation de loueurs et de locataires de vans.</p>
    </div>

    <div class="project">
      <h4>Tech stack</h4>
      <div class="stack">
        <a href="#">Ruby on Rails</a><a href="#">JavaScript</a><a href="#">HTML</a><a href="#">CSS</a><a href="#">Bootstrap</a><a href="#">postgreSQL</a>
      </div>
    </div>
      <div class="link-to">
        <a href="https://github.com/PauFou/caravana" class="link-project" style="margin-right:10px"><i class="fa-brands fa-github icon"></i>Voir le code</a>
        <a href="https://caravana-adrih1.herokuapp.com/" class="link-project" style="margin-left:10px"><i class="fa-brands fa-chrome icon"></i>Voir le projet</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/deflavour.html.erb
<div class="container">
  <h1 class="title-product"> DeFlavour </h1>
  <div class="product-photos">
    <div class="big-card" style="height:400px;width:50%">

      <img src="https://res.cloudinary.com/dm52xbw1e/image/upload/v1663148797/Capture_d_e%CC%81cran_2022-09-14_a%CC%80_11.45.52_dpns6j.png" alt="Deflavour" style="width:100%; height:100%;border-radius: 5px;">
    </div>
    <div class="cards-feature" style="height:400px;width:50%">
      <div class="card-category" style="background-position: top; background-image: url(https://res.cloudinary.com/dm52xbw1e/image/upload/v1663163945/www.deflavour.com__4_q9bgqy.png)">
      </div>
      <div class="card-category" style="background-position: top; background-image: url(https://res.cloudinary.com/dm52xbw1e/image/upload/v1663163868/Capture_d_e%CC%81cran_2022-09-14_a%CC%80_15.57.39_trffms.png)">
      </div>
      <div class="card-category" style="background-position: top; background-image: url(https://res.cloudinary.com/dm52xbw1e/image/upload/v1663163950/www.deflavour.com__5_mcwrqi.png)">
      </div>
      <div class="card-category" style="background-position: top; background-image: url(https://res.cloudinary.com/dm52xbw1e/image/upload/v1663164213/www.deflavour.com_maindashboard_cdcruk.png)">
      </div>
    </div>
  </div>
  <div class="product-infos">
    <div class="infos-special">
      <h4>Projet d'étude</h4>
      <p>Site crée pendant ma formation au Wagon.</p>
    </div>
    <div class="product-base">
      <h4>A propos</h4>
      <p>Créer un algorithme qui, en fonction des bouteilles que vous appréciez, sera capable de vous porposer un pannel de 5 spiritueux faits pour vous.</p>
    </div>

    <div class="project">
      <h4>Tech stack</h4>
      <div class="stack">
        <a href="#">Ruby on Rails</a><a href="#">JavaScript</a><a href="#">HTML</a><a href="#">CSS</a><a href="#">Bootstrap</a><a href="#">postgreSQL</a>
      </div>
    </div>
      <div class="link-to">
        <a href="https://github.com/PauFou/deflavour" class="link-project" style="margin-right:10px"><i class="fa-brands fa-github icon"></i>Voir le code</a>
        <a href="https://www.deflavour.com/" class="link-project" style="margin-left:10px"><i class="fa-brands fa-chrome icon"></i>Voir le projet</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
    <div id="banner" class="cards">
      <div class="avatar-paul">
        <img src="https://res.cloudinary.com/dm52xbw1e/image/upload/v1662968669/tete_paul_du3tow.jpg" alt="Paul Fournier" class="avatar">
      </div>
      <div class="infos">
        <h1>Hey👋, Je suis Paul <br>
          Un Dévelopeur Fullstack <br>
          basé à Paris.</h1>
        <h3>J'aide les entreprises à atteindre leurs objectifs.</h3>
          <a href="#">
            <button class="my-email">
              <i class="fa-regular fa-envelope envelope"></i>pfournier597@gmail.com
            </button>
          </a>
      </div>
  </div>

  <div id="gallery">
    <p><i class="fa-solid fa-arrow-down arrow-down"></i> PROJETS SELECTIONNES</p>
    <div class='project-cards'>
      <%= link_to deflavour_path do %>
        <div class="project-card" id="deflavour">

          <div class="stack">
            <button>Ruby on Rails</button><button>JavaScript</button><button>HTML</button><button>CSS</button><button>Bootstrap</button><button>postgreSQL</button>
          </div>
          <span>DeFlavour</span>
        </div>

      <% end %>
      <%= link_to caravana_path do %>
        <div class="project-card" id="caravana">
          <div class="stack">
            <button>Ruby on Rails</button><button>JavaScript</button><button>HTML</button><button>CSS</button><button>Bootstrap</button><button>postgreSQL</button>
          </div>
          <span>Caravana</span>
        </div>
      <% end %>
    </div>
  </div>
  <div id="contact-me">
    <h2>Contactez-moi</h2>
    <h3>Si vous cherchez à embaucher un developeur web,<br>
    Je suis actuellement disponible pour un poste en freelance.</h3>
    <button class="my-email">
      <i class="fa-regular fa-envelope envelope"></i>pfournier597@gmail.com
    </button>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div id="made-by">
    <h4>Made by Paul Fournier — Copyright 2022</h4>
  </div>
  <div id="social-media-icon">
    <a href="#"><i class="fa-brands fa-linkedin"></i></a>
    <a href="#"><i class="fa-brands fa-github"></i></a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<header>
  <div class="navbar">
    <div class="logo">
      <%= link_to root_path do %>
        PauFou
      <% end %>
    </div>
    <div class="items">
      <%= link_to "Contact", root_path(:anchor => "contact-me"), class: "contact item"  %>
      <%= link_to "Work", root_path(:anchor => "gallery"), class: "work item" %>
      <%= link_to "Home", root_path, class: "home item" %>
    </div>
  </div>
</header>